### ISSUE TITLE
The specified bucket does not exist

### ISSUE THREAD

**Issue by jfwu777** [openproblems-bio/neurips2021_multimodal_topmethods#17]
Is the data stored in s3 removed?
It keeps hinting "The specified bucket does not exist" when I try to sync the data via src/sync_datasets.sh

**Comment by LuckyMD** [comment]
Hi @jfwu777,
We've actually just moved the data to the public branch on s3. The data is now also available on GEO [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE194122)
