### ISSUE TITLE
Hello, does anyone know where I can find the Phase 2 data?

### ISSUE THREAD

**Issue by wukaiyeah** [openproblems-bio/neurips2021_multimodal_topmethods#20]
HELP, does anyone know where I can find the Phase 2 data? I am working on it.

**Comment by rcannood** [comment]
You can find the whole dataset [here](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE194122).

Specifically, the Phase 2 data can be found at `s3://openproblems-bio/public/phase2-private-data/`, which you can retrieve by running `src/sync_datasets.sh` from the root of this repository.
