### ISSUE TITLE
reproduce results for task2

### ISSUE THREAD

**Issue by tamiryam** [openproblems-bio/neurips2021_multimodal_topmethods#22]
Hi,

I am trying to reproduce the results of task-2 for the two top methods.
For both of them, I get errors while running the test.sh script.

CLUE:
I get the following line in the .command.log
![image](https://user-images.githubusercontent.com/52567561/167259842-77122425-4a0f-49f9-aeb7-b8f73ddac4fc.png)
and during the execution I get:
![image](https://user-images.githubusercontent.com/52567561/167259888-cff87096-c83f-4c98-a974-d0494ede301a.png)

NOVEL:
I get the following output 
![image](https://user-images.githubusercontent.com/52567561/167260001-f45e76bd-2b96-44ac-a12f-a82e1f1969e2.png)

Are those familiar problems?
I run the execute the repo on my laptop using Ubunto 20 through wsl

Thanks,
Tamir.

**Comment by LuckyMD** [comment]
Hi Tamir,

Sorry for the delayed response. Did you solve the above issues?

**Comment by tamiryam** [comment]
not yet, but I am trying to reinstall everything from the beginning.
